// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// chooseC
double chooseC(double n, double k);
RcppExport SEXP svisits_chooseC(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(chooseC(n, k));
    return __result;
END_RCPP
}
// adjust_Rcpp_min
NumericVector adjust_Rcpp_min(NumericMatrix mat, double prob);
RcppExport SEXP svisits_adjust_Rcpp_min(SEXP matSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    __result = Rcpp::wrap(adjust_Rcpp_min(mat, prob));
    return __result;
END_RCPP
}
// adjust_R_Rcpp_short_binomial
NumericVector adjust_R_Rcpp_short_binomial(NumericMatrix mat, double prob);
RcppExport SEXP svisits_adjust_R_Rcpp_short_binomial(SEXP matSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    __result = Rcpp::wrap(adjust_R_Rcpp_short_binomial(mat, prob));
    return __result;
END_RCPP
}

