# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chooseC <- function(n, k) {
    .Call('svisits_chooseC', PACKAGE = 'svisits', n, k)
}

adjust_Rcpp_min <- function(mat, prob) {
    .Call('svisits_adjust_Rcpp_min', PACKAGE = 'svisits', mat, prob)
}

adjust_R_Rcpp_short_binomial <- function(mat, prob) {
    .Call('svisits_adjust_R_Rcpp_short_binomial', PACKAGE = 'svisits', mat, prob)
}

